const createUnits = [
  {
    objectName: "barracks",

    gorjacar: {
      unitName: "Gorjačar",
      costWood: 100,
      costClay: 100,
      costIron: 100,
      costWheat: 100,
      timeToBuild: 10,
      attack: 10,
      defense: 1,
      type: "infantry",
      upkeep: 1,
    },
    sulicar: {
      unitName: "Suličar",
      costWood: 200,
      costClay: 200,
      costIron: 200,
      costWheat: 200,
      timeToBuild: 20,
      attack: 5,
      defense: 15,
      type: "infantry",
      upkeep: 2,
    },
    long_bowman: {
      unitName: "Long Bowman",
      costWood: 200,
      costClay: 200,
      costIron: 200,
      costWheat: 200,
      timeToBuild: 20,
      attack: 15,
      defense: 5,
      type: "archer",
      upkeep: 2,
    },
    crossbow: {
      unitName: "Crossbow",
      costWood: 500,
      costClay: 500,
      costIron: 500,
      costWheat: 500,
      timeToBuild: 40,
      attack: 25,
      defense: 10,
      type: "archer",
      upkeep: 3,
    },
  },

  {
    objectName: "stable",

    jadan_konj: {
      unitName: "Jadn konj",
      costWood: 50,
      costClay: 50,
      costIron: 50,
      costWheat: 50,
      timeToBuild: 10,
      attack: 10,
      defense: 5,
      type: "cavalry",
      upkeep: 2,
    },

    tevtonskiVitez: {
      unitName: "Tevtonski vitez",
      costWood: 100,
      costClay: 100,
      costIron: 100,
      costWheat: 100,
      timeToBuild: 10,
      attack: 40,
      defense: 20,
      type: "cavalry",
      upkeep: 10,
    },
    paladin: {
      unitName: "Paladin",
      costWood: 200,
      costClay: 200,
      costIron: 200,
      costWheat: 200,
      timeToBuild: 20,
      attack: 15,
      defense: 40,
      type: "cavalry",
      upkeep: 5,
    },
  },
]; //END ARRAY

export { createUnits };
